import * as fs from "fs";
import * as path from "path";

function stringifyValue(value: unknown): string {
  if (typeof value === "string") {
    return JSON.stringify(value);
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (value === null) {
    return "null";
  }
  if (Array.isArray(value)) {
    return JSON.stringify(value);
  }
  if (typeof value === "object") {
    return JSON.stringify(value);
  }
  return JSON.stringify(value);
}

function generateBrand(config: Record<string, unknown>): string {
  const entries = Object.entries(config)
    .map(([key, value]) => `  ${key}: ${stringifyValue(value)}`)
    .join(",\n");

  return `// This file is auto-generated by generate-brand.ts
// Do not edit this file manually

export const brand = {
${entries}
} as const;

// Type-safe brand variables
export type BrandT = typeof brand;
`;
}

function main() {
  const brandName = process.argv[2];

  if (!brandName) {
    console.error("Error: Brand name is required");
    console.log("Usage: tsx scripts/generate-brand.ts <brand-name>");
    process.exit(1);
  }

  const configPath = path.join(process.cwd(), "brands", `${brandName}.json`);
  const brandTsPath = path.join(process.cwd(), "brand.ts");

  // Check if config file exists
  if (!fs.existsSync(configPath)) {
    console.error(`Error: Config file not found: ${configPath}`);
    console.log(`Available configs in brands/ directory:`);
    const configsDir = path.join(process.cwd(), "brands");
    if (fs.existsSync(configsDir)) {
      const files = fs
        .readdirSync(configsDir)
        .filter((file) => file.endsWith(".json"))
        .map((file) => file.replace(".json", ""));
      if (files.length > 0) {
        files.forEach((file) => console.log(`  - ${file}`));
      } else {
        console.log("  (no config files found)");
      }
    }
    process.exit(1);
  }

  try {
    // Read and parse config file
    const configContent = fs.readFileSync(configPath, "utf-8");
    const config: Record<string, unknown> = JSON.parse(configContent);

    // Generate env.ts content
    const brandTsContent = generateBrand(config);

    // Write env.ts file
    fs.writeFileSync(brandTsPath, brandTsContent, "utf-8");

    console.log(`✓ Successfully generated brand.ts from ${brandName} config`);
    console.log(`  Config: ${configPath}`);
    console.log(`  Output: ${brandTsPath}`);
  } catch (error) {
    console.error("Error processing config:", error);
    process.exit(1);
  }
}

main();
